/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API ヘルスチェック
         * @description APIサーバーの稼働状況を確認
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API稼働中 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** @example Baby Log API is running */
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ユーザー登録
         * @description 新規ユーザーを登録し、JWTトークンを返す
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserRegistrationRequest"];
                };
            };
            responses: {
                /** @description 登録成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードでログインし、JWTトークンを返す
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserLoginRequest"];
                };
            };
            responses: {
                /** @description ログイン成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description 認証失敗 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * ログアウト
         * @description JWTトークンを無効化
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ログアウト成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 認証ユーザー情報取得
         * @description 現在認証中のユーザー情報を取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ユーザー情報取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プロフィール取得
         * @description 認証ユーザーのプロフィール情報を取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description プロフィール取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * プロフィール更新
         * @description 認証ユーザーのプロフィール情報を更新
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description プロフィール更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 育児記録一覧取得
         * @description 認証ユーザーの育児記録とパートナーの記録を取得
         */
        get: {
            parameters: {
                query?: {
                    /** @description ページ番号 */
                    page?: number;
                    /** @description 1ページあたりの件数 */
                    per_page?: number;
                    /** @description 記録タイプでフィルタ */
                    type?: components["schemas"]["RecordType"];
                    /** @description 開始日（YYYY-MM-DD） */
                    date_from?: string;
                    /** @description 終了日（YYYY-MM-DD） */
                    date_to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 記録一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordListResponse"];
                    };
                };
                /** @description 未認証 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 育児記録作成
         * @description 新しい育児記録を作成
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordCreateRequest"];
                };
            };
            responses: {
                /** @description 記録作成成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 記録ID */
                id: string;
            };
            cookie?: never;
        };
        /**
         * 育児記録詳細取得
         * @description 指定したIDの育児記録を取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 記録ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 記録取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                    };
                };
                /** @description 記録が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * 育児記録更新
         * @description 指定したIDの育児記録を更新（自分の記録のみ更新可能）
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 記録ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordUpdateRequest"];
                };
            };
            responses: {
                /** @description 記録更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Record"];
                    };
                };
                /** @description 他人の記録は更新できない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 記録が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 育児記録削除
         * @description 指定したIDの育児記録を削除（自分の記録のみ削除可能）
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 記録ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 記録削除成功 */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 他人の記録は削除できない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description 記録が見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partnerships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * パートナーシップ一覧取得
         * @description 自分に関連するパートナーシップリクエストを取得
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description パートナーシップ一覧取得成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partnership"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * パートナーシップリクエスト送信
         * @description 他のユーザーにパートナーシップリクエストを送信
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnershipCreateRequest"];
                };
            };
            responses: {
                /** @description リクエスト送信成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partnership"];
                    };
                };
                /** @description バリデーションエラー */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/partnerships/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description パートナーシップID */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * パートナーシップ応答
         * @description 受信したパートナーシップリクエストに応答（承認/拒否）
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description パートナーシップID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PartnershipUpdateRequest"];
                };
            };
            responses: {
                /** @description 応答成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Partnership"];
                    };
                };
                /** @description 他人のリクエストには応答できない */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description パートナーシップが見つからない */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example [
             *       "Email has already been taken"
             *     ] */
            errors?: string[];
        };
        UserRegistrationRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
            /** @example password123 */
            password_confirmation: string;
            /** @example 山田太郎 */
            display_name: string;
        };
        UserLoginRequest: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example password123 */
            password: string;
        };
        AuthResponse: {
            user?: components["schemas"]["User"];
            /**
             * @description JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token?: string;
        };
        User: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example 山田太郎 */
            display_name?: string;
            /**
             * Format: uri
             * @example https://example.com/avatar.jpg
             */
            avatar_url?: string | null;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            updated_at?: string;
        };
        UserUpdateRequest: {
            /** @example 山田次郎 */
            display_name?: string;
            /**
             * Format: uri
             * @example https://example.com/new_avatar.jpg
             */
            avatar_url?: string | null;
        };
        /** @enum {string} */
        RecordType: "milk" | "diaper" | "sleep" | "vaccination" | "growth";
        Record: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            user_id?: string;
            type?: components["schemas"]["RecordType"];
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            timestamp?: string;
            /**
             * @description 記録タイプに応じたメタデータ
             * @example {
             *       "amount": 120,
             *       "unit": "ml",
             *       "notes": "順調に飲みました"
             *     }
             */
            metadata?: Record<string, never>;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at?: string;
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            updated_at?: string;
        };
        RecordCreateRequest: {
            type: components["schemas"]["RecordType"];
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            timestamp: string;
            /**
             * @description 記録タイプに応じたメタデータ
             * @example {
             *       "amount": 120,
             *       "unit": "ml",
             *       "notes": "順調に飲みました"
             *     }
             */
            metadata?: Record<string, never>;
        };
        RecordUpdateRequest: {
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            timestamp?: string;
            /**
             * @description 記録タイプに応じたメタデータ
             * @example {
             *       "amount": 150,
             *       "unit": "ml",
             *       "notes": "よく飲みました"
             *     }
             */
            metadata?: Record<string, never>;
        };
        RecordListResponse: {
            records?: components["schemas"]["Record"][];
            pagination?: components["schemas"]["PaginationInfo"];
        };
        PaginationInfo: {
            /** @example 1 */
            current_page?: number;
            /** @example 20 */
            per_page?: number;
            /** @example 5 */
            total_pages?: number;
            /** @example 98 */
            total_count?: number;
        };
        /** @enum {string} */
        PartnershipStatus: "pending" | "accepted" | "declined";
        Partnership: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            user1?: components["schemas"]["User"];
            user2?: components["schemas"]["User"];
            status?: components["schemas"]["PartnershipStatus"];
            /**
             * Format: date-time
             * @example 2024-01-15T10:30:00Z
             */
            created_at?: string;
        };
        PartnershipCreateRequest: {
            /**
             * Format: email
             * @example partner@example.com
             */
            partner_email: string;
        };
        PartnershipUpdateRequest: {
            /**
             * @example accepted
             * @enum {string}
             */
            status: "accepted" | "declined";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
